Repository jenkinsci/coverage-badges-extension-plugin, pull requests merged in 2023-12, with the labels that each got.

#1 Update name on pom and index.jelly
  pom.xml
  src/main/resources/index.jelly
Labels: skip-changelog

#2 Add badges
  README.md
  src/main/resources/index.jelly
Labels: skip-changelog

#4 Fix spelling intructionCoverage -> instructionCoverage
  README.md
  src/main/java/io/jenkins/plugins/coveragebadge/CoverageParameterResolverExtension.java
  src/test/java/io/jenkins/plugins/coveragebadge/CoverageParameterResolverExtensionTest.java
Labels: skip-changelog

#6 Fix codeowner
  .github/CODEOWNERS
Labels: skip-changelog

#7 Increase test coverage
  src/main/java/io/jenkins/plugins/coveragebadge/CoverageParameterResolverExtension.java
  src/test/java/io/jenkins/plugins/coveragebadge/CoverageParameterResolverExtensionTest.java
  src/test/resources/pipelines/coverage_only.groovy
  src/test/resources/pipelines/no_coverage.groovy
  src/test/resources/pipelines/tests_only.groovy
Labels: skip-changelog, tests

#5 First plugin release
  .github/release-drafter.yml
  .mvn/maven.config
Labels: enhancement

#3 Use shorter text for easier reading
  README.md
Labels: documentation
